import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=' bg-yellow-600'>
          <ul className='flex flex-row gap-4 justify-center pt-8 pb-8'>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/blogs">Blogs</Link></li>
          </ul>
        </div>
        <div className='mt-10'>
          {children}
        </div>
        
        </body>
    </html>
  )
}
